# Generated by Django 6.0.2 on 2026-02-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название команды')),
                ('description', models.TextField(verbose_name='Описание команды')),
                ('discipline', models.CharField(max_length=100, verbose_name='Дисциплина')),
                ('goal', models.CharField(max_length=200, verbose_name='Цель команды')),
                ('logo', models.ImageField(blank=True, upload_to='team/', verbose_name='Логотип команды')),
            ],
            options={
                'verbose_name': 'Информация о команде',
                'verbose_name_plural': 'Информация о команде',
            },
        ),
        migrations.DeleteModel(
            name='About',
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(verbose_name='Дата матча'),
        ),
        migrations.AlterField(
            model_name='match',
            name='opponent',
            field=models.CharField(max_length=100, verbose_name='Соперник'),
        ),
        migrations.AlterField(
            model_name='match',
            name='result',
            field=models.CharField(max_length=50, verbose_name='Результат'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='nickname',
            field=models.CharField(max_length=50, verbose_name='Никнейм'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, upload_to='players/', verbose_name='Фото игрока'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(max_length=50, verbose_name='Роль'),
        ),
    ]
