# Generated by Django 6.0.2 on 2026-03-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_teaminfo_delete_about_alter_match_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminfo',
            name='creator',
            field=models.URLField(blank=True),
        ),
    ]
